name: fastar
channels:
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cuda-nvrtc=12.4.127
  - cuda-version=12.4
  - cudnn=9.2.1.18
  - ld_impl_linux-64=2.40
  - libcublas=12.4.5.8
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.5.0
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - addict==2.4.0
      - argparse==1.4.0
      - backcall==0.2.0
      - boto3==1.38.25
      - botocore==1.38.25
      - click==8.2.1
      - distro==1.9.0
      - filetype==1.2.0
      - fire==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - groundingdino-py==0.4.0
      - grpcio==1.71.0
      - huggingface-hub==0.24.7
      - idna==3.7
      - ipython==8.12.3
      - jmespath==1.0.1
      - markdown==3.8
      - markupsafe==3.0.2
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.64.0
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - pickleshare==0.7.5
      - pillow==11.1.0
      - pillow-heif==0.22.0
      - protobuf==4.21.2
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pybboxes==0.1.6
      - pycocotools==2.0.8
      - pyparsing==3.2.3
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests-toolbelt==1.0.0
      - roboflow==1.1.64
      - s3transfer==0.13.0
      - sahi==0.11.23
      - scipy==1.15.3
      - seaborn==0.13.2
      - segment-anything==1.0
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - supervision==0.6.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - timm==1.0.15
      - torch==2.5.0
      - torchvision==0.20.0
      - triton==3.1.0
      - tzdata==2025.2
      - ultralytics==8.3.146
      - ultralytics-thop==2.0.14
      - werkzeug==3.1.3
      - wget==3.2
      - yapf==0.43.0
      - yolov5==7.0.14
